version: '3'
services:
  nginx:
    container_name: asthma-nginx
    build:
      context: ./nginx
    networks:
      - internal
    volumes:
      - ./nginx/image-files/etc/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx:/etc/nginx/html
    depends_on:
      - mysql
      - api
      - redis
    ports:
      - 80:80
      - 443:443

  api:
    container_name: asthma-api
    build:
      context: ./api
    depends_on:
        - mysql
    env_file: .env
    networks:
      - internal
    environment:
      - PHP_ENABLE_XDEBUG=${PHP_ENABLE_XDEBUG}
    volumes:
     - ./api/image-files/etc/nginx/nginx.conf:/etc/nginx/nginx.conf
     - ./api:/srv

  # backend:
  #   container_name: backend
  #   build:
  #     context: ./backend
  #     dockerfile: ./Dockerfile.dev       # For development
  #     #dockerfile: ./Dockerfile       # For deployment
  #   depends_on:
  #       - api
  #   env_file: .env
  #   networks:
  #     - internal
  #   volumes:
  #    - ./backend/image-files/etc/nginx/nginx.conf:/etc/nginx/nginx.conf
  #    - ./backend/src:/app/src

  # frontend:
  #   container_name: frontend
  #   build:
  #     context: ./frontend
  #     dockerfile: ./Dockerfile.dev       # For development
  #     #dockerfile: ./Dockerfile       # For deployment
  #   depends_on:
  #       - api
  #   env_file: .env
  #   networks:
  #     - internal
  #   volumes:
  #    - ./frontend/image-files/etc/nginx/nginx.conf:/etc/nginx/nginx.conf
  #    - ./frontend/src:/app/src

  redis:
    container_name: asthma-redis
    image: redis:latest
    networks:
      - internal

  mysql:
    container_name: asthma-mysql
    image: mysql:5.6
    restart: always
    networks:
      - internal
    env_file: .env
    ports:
      - 3307:3006
    volumes:
      - mysql_data:/var/lib/mysql

networks:
  internal:
    driver: bridge

volumes:
  mysql_data:
